
GRAVITY = 9.81

# Mechanical constants
WHEEL_OUTER_RADIUS = .025
WHEEL_INNER_RADIUS = .015
WHEEL_MASS = .02
WHEEL_MOMENT_OF_INERTIA = WHEEL_MASS * (WHEEL_OUTER_RADIUS ** 2 + WHEEL_INNER_RADIUS** 2) # kg m^2
FRICTION_COEFFICIENT = 0.5

TOTAL_MASS = 0.30